---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nfs-client-provisioner
  namespace: kube-system
spec:
  chart: nfs-client-provisioner
  repo: https://charts.helm.sh/stable
  targetNamespace: default
  set:
    image.repository: quay.io/external_storage/nfs-client-provisioner-arm
    nfs.server: 10.0.0.1
    nfs.path: /mnt/sda1
    storageClass.archiveOnDelete: "false"
