apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: test-things-on-top-of-other-things-de
  namespace: default
spec:
  secretName: test-things-on-top-of-other-things-de-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: test.things-on-top-of-other-things.de
  dnsNames:
  - test.things-on-top-of-other-things.de
